apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  containers:
  - name: mycontainer
    image: nginxinc/nginx-unprivileged
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false